//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekaraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Stavka_narudzbeProdaje = new HashSet<Stavka_narudzbeProdaje>();
            this.StavkaRacunas = new HashSet<StavkaRacuna>();
        }
    
        public int ID_proizvoda { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<double> Cijena { get; set; }
        public Nullable<int> Zaliha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_narudzbeProdaje> Stavka_narudzbeProdaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacuna> StavkaRacunas { get; set; }
    }
}
