//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekaraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.StavkaRacunas = new HashSet<StavkaRacuna>();
        }
    
        public int ID_racuna { get; set; }
        public Nullable<int> ID_zaposlenika { get; set; }
        public string NacinPlacanja { get; set; }
        public Nullable<double> Popust { get; set; }
        public Nullable<double> PocetniIznos { get; set; }
        public Nullable<double> KonacniIznos { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacuna> StavkaRacunas { get; set; }
    }
}
