//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekaraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_narudzbeProdaje
    {
        public int ID_narudzbeProdaje { get; set; }
        public int ID_proizvoda { get; set; }
        public Nullable<double> Kolicina { get; set; }
    
        public virtual NarudzbaProdaje NarudzbaProdaje { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
